# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Liberty Buildpack"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml", "templates/app.tmpl", "templates/features.tmpl", "templates/default-http-endpoint.tmpl"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    description = "The SHA256 hash of the external configuration archive"
    name = "BP_LIBERTY_EXT_CONF_SHA256"

  [[metadata.configurations]]
    build = true
    default = "0"
    description = "The number of directory components to strip from the external configuration archive"
    name = "BP_LIBERTY_EXT_CONF_STRIP"

  [[metadata.configurations]]
    build = true
    description = "The download location of the external configuration"
    name = "BP_LIBERTY_EXT_CONF_URI"

  [[metadata.configurations]]
    build = true
    description = "The version of the Liberty configuration"
    name = "BP_LIBERTY_EXT_CONF_VERSION"

  [[metadata.configurations]]
    build = true
    default = "full"
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Context root to use for app"
    launch = true
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@22.0.0.5"
    sha256 = "b5e78f0a6151ccc73d9fe4814790507ac595bb35b31ece04cf641f00089fa077"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.5/openliberty-runtime-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.6:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-jakartaee9"
    name = "Open Liberty (Jakarta EE9)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee9@22.0.0.6"
    sha256 = "17b2890a52ff13f9f8426dd9ce99314399e0903a6aa3b653472b1f4610e00b91"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee9/22.0.0.6/openliberty-jakartaee9-22.0.0.6.zip"
    version = "22.0.6"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@22.0.0.5"
    sha256 = "644b48c3de536d88b110c8d8d459b07452a6fd4796f2b950fdc937b3d3a117c3"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/22.0.0.5/openliberty-javaee8-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-webProfile9"
    name = "Open Liberty (Web Profile 9)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile9@22.0.0.5"
    sha256 = "a1ffbd5ad92c7508d9dabeec7e1e4501b55c68b671923253d4a5b550c4ff10e3"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile9/22.0.0.5/openliberty-webProfile9-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@22.0.0.5"
    sha256 = "8f6716343162d8657917b4d188e0affd3c0c169c6c7a2cc771b14bad7353f266"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/22.0.0.5/openliberty-webProfile8-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-microProfile5"
    name = "Open Liberty (Micro Profile 5)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile5@22.0.0.5"
    sha256 = "47cf414cae6e1930020bfe83a9949573eddacfc937ba8e20150c7b24ac6db6fe"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile5/22.0.0.5/openliberty-microProfile5-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@22.0.0.5"
    sha256 = "824be8903abcf2a968069f445c2bc594f957beb5653cf533039f46c860698645"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/22.0.0.5/openliberty-microProfile4-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.5:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@22.0.0.5"
    sha256 = "e7083b1029d2df7eb6f008e543bb835e84f4ec23a30de8b052cd087b356f0515"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/22.0.0.5/openliberty-kernel-22.0.0.5.zip"
    version = "22.0.5"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "*"
