# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that provides the Open Liberty and WebSphere Liberty runtimes."
  homepage = "https://github.com/paketo-buildpacks/liberty"
  id = "paketo-buildpacks/liberty"
  keywords = ["java", "javaee", "liberty"]
  name = "Paketo Buildpack for Liberty"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/vnd.syft+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/liberty/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/main", "bin/helper", "buildpack.toml", "templates/server.tmpl", "templates/app.tmpl", "templates/features.tmpl", "templates/expose-default-endpoint.xml"]
  pre-package = "scripts/build.sh"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "the application server to use"
    name = "BP_JAVA_APP_SERVER"

  [[metadata.configurations]]
    build = true
    default = "ol"
    description = "Install type of Liberty"
    launch = false
    name = "BP_LIBERTY_INSTALL_TYPE"

  [[metadata.configurations]]
    build = true
    default = "*"
    description = "Which version of the Liberty runtime to install"
    launch = false
    name = "BP_LIBERTY_VERSION"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "The Liberty profile to install"
    launch = false
    name = "BP_LIBERTY_PROFILE"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "Name of the server to use"
    launch = true
    name = "BP_LIBERTY_SERVER_NAME"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Context root to use for app"
    launch = true
    name = "BP_LIBERTY_CONTEXT_ROOT"

  [[metadata.configurations]]
    build = false
    default = ""
    description = "Sets the logging level"
    launch = true
    name = "BPL_LIBERTY_LOG_LEVEL"

  [[metadata.configurations]]
    build = true
    default = ""
    description = "A space separated list of liberty features to install."
    launch = false
    name = "BP_LIBERTY_FEATURES"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-full"
    name = "Open Liberty (All Features)"
    purl = "pkg:maven/io.openliberty/openliberty-runtime@22.0.0.9"
    sha256 = "640a828a9bba1c73c5200c2489de35e71fb204e58e5e10b4c3297381bd476927"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-runtime/22.0.0.9/openliberty-runtime-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.10:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-jakartaee9"
    name = "Open Liberty (Jakarta EE9)"
    purl = "pkg:maven/io.openliberty/openliberty-jakartaee9@22.0.0.10"
    sha256 = "4d747244ecfe28a525b432541b7a0bac2944e898ebdff7c52b744868e29e1f6f"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-jakartaee9/22.0.0.10/openliberty-jakartaee9-22.0.0.10.zip"
    version = "22.0.10"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-javaee8"
    name = "Open Liberty (Java EE8)"
    purl = "pkg:maven/io.openliberty/openliberty-javaee8@22.0.0.9"
    sha256 = "d1f2da1ba23fb899511bd0d430e636e59719dc33e564d7786fe48fe761ed0ac9"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-javaee8/22.0.0.9/openliberty-javaee8-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-webProfile9"
    name = "Open Liberty (Web Profile 9)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile9@22.0.0.9"
    sha256 = "a12bf09ff84d69be92bfda6eb54efde7121dbd0583681256e77892681625459f"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile9/22.0.0.9/openliberty-webProfile9-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-webProfile8"
    name = "Open Liberty (Web Profile 8)"
    purl = "pkg:maven/io.openliberty/openliberty-webProfile8@22.0.0.9"
    sha256 = "c964a86ebf8156829a11b8764a75011aaaf2ad5f481c1a85601e525cb235732b"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-webProfile8/22.0.0.9/openliberty-webProfile8-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-microProfile5"
    name = "Open Liberty (Micro Profile 5)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile5@22.0.0.9"
    sha256 = "520c1273f55e754311076d95819a99c77ff930e615050509e660731431a67370"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile5/22.0.0.9/openliberty-microProfile5-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-microProfile4"
    name = "Open Liberty (Micro Profile 4)"
    purl = "pkg:maven/io.openliberty/openliberty-microProfile4@22.0.0.9"
    sha256 = "d30d1371a50fa6d6dc340eed17c7bdd0dfaa8def2deb112079bdbf14aae90400"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-microProfile4/22.0.0.9/openliberty-microProfile4-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "open-liberty-runtime-kernel"
    name = "Open Liberty (Kernel)"
    purl = "pkg:maven/io.openliberty/openliberty-kernel@22.0.0.9"
    sha256 = "088c1c4cdec332f142d0229c8455ce2e649d7828ea84bada8b373cb55b20f40a"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/io/openliberty/openliberty-kernel/22.0.0.9/openliberty-kernel-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "EPL-1.0"
      uri = "https://raw.githubusercontent.com/OpenLiberty/open-liberty/integration/LICENSE"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-kernel"
    name = "WebSphere Liberty (Kernel)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-kernel@22.0.0.9"
    sha256 = "fd252457d4ae7af048891ee63e6fcff446b908c649dce0a8d5d803ee31e01cdd"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-kernel/22.0.0.9/wlp-kernel-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-jakartaee9"
    name = "WebSphere Liberty (Jakarta EE9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-jakartaee9@22.0.0.9"
    sha256 = "029137715d9ac740861104c8657dc48082cc268a33c2fd2ba84e9fd0e93ae8c0"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-jakartaee9/22.0.0.9/wlp-jakartaee9-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee8"
    name = "WebSphere Liberty (Java EE8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee8@22.0.0.9"
    sha256 = "bdbfa5ead55a71e3a9e8876639f4187b80c20527f8b044f4ed1875e8273b1625"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee8/22.0.0.9/wlp-javaee8-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-javaee7"
    name = "WebSphere Liberty (Java EE7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-javaee7@22.0.0.9"
    sha256 = "6beed4680d62c24270f1b3499d7ae02b87135a310cfb5206b29ba7d6c652faad"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-javaee7/22.0.0.9/wlp-javaee7-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile9"
    name = "WebSphere Liberty (Web Profile 9)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile9@22.0.0.9"
    sha256 = "c21d9da7aa9ae24836fcf7eb17a88ea177f4eb212c2926adc5fc513e9e1aa343"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile9/22.0.0.9/wlp-webProfile9-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile8"
    name = "WebSphere Liberty (Web Profile 8)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile8@22.0.0.9"
    sha256 = "f656e05a895fe1bf6b40b2014e35f8eea48230370b75ebda07dcb52022fd53f6"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile8/22.0.0.9/wlp-webProfile8-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:ibm:websphere_application_server:22.0.0.9:*:*:*:liberty:*:*:*"]
    id = "websphere-liberty-runtime-webProfile7"
    name = "WebSphere Liberty (Web Profile 7)"
    purl = "pkg:maven/com.ibm.websphere.appserver.runtime/wlp-webProfile7@22.0.0.9"
    sha256 = "d588a1acac85c7528c03571e3b76fff0885cad80b16168e681e5023231891d86"
    stacks = ["io.buildpacks.stacks.bionic", "*"]
    uri = "https://repo1.maven.org/maven2/com/ibm/websphere/appserver/runtime/wlp-webProfile7/22.0.0.9/wlp-webProfile7-22.0.0.9.zip"
    version = "22.0.9"

    [[metadata.dependencies.licenses]]
      type = "Proprietary"
      uri = "https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/downloads/wlp/22.0.0.8/lafiles/runtime/en.html"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "*"
